# Site settings
title: gBrock
email: contact@gbrock.com
description: > # this means to ignore newlines until "baseurl:"
  I create custom websites and web applications.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://gbrock.com" # the base hostname & protocol for your site
github_username:  gbrock

# Build settings
markdown: kramdown
