# Site settings
title: gBrock
email: contact@gbrock.com
description: > # this means to ignore newlines until "baseurl:"
  Greg creates things, mostly websites
copyright: Content © gBrock 2009-2015
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://gbrock.com" # the base hostname & protocol for your site
github_username:  gbrock
twitter_username:  GeeBrawk
permalink: /blog/:categories/:title
paginate: 3
paginate_path: "blog/page:num/"
menu: default
include: [.htaccess]

# Build settings
markdown: MyFormatter
navigation:
 - title: Blog
   url: /blog
 # - title: Contact
 #   url: /contact
defaults: 
  - # Every post uses the Post layout
    scope:
      path: "blog"
      type: "pages"
    values:
      layout: "default"
  - # Every post uses the Post layout
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - # Every post uses the Post layout
    scope:
      path: ""
      type: "drafts"
    values:
      layout: "draft"